# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
						 https://alexlais.github.io
baseurl                  : # the subpath of your site, e.g. "/blog"
                         /002/index.html
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
                         alexlais/002

