# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings

# the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
url: "https://alexlais.github.io"

# the subpath of your site, e.g. "/blog" 
# NOTE "/blog/" should be better so that angular knows its a folder for certain and not a file
baseurl: "/002/index.html"

# GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
repository: "alexlais/002"

